[package]
name = "SOElauncher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.2.29"
SOEcommon = {path="../SOEcommon"}
webbrowser = "0.5.5"
