name: CI

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - { name: "Checkout the code", uses: actions/checkout@v2 }

      - name: Setup Rust cache
        uses: actions/cache@v2
        with:
          key: ${{ matrix.os }}-${{ hashFiles('src-tauri/Cargo.lock') }}
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            ./src-tauri/target

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with: { toolchain: stable }

      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y --no-install-recommends -y libgtk-3-dev libgtksourceview-3.0-dev webkit2gtk-4.0 libappindicator3-dev webkit2gtk-driver xvfb

      - name: Build launcher
        working-directory: ./SOElauncher
        run: |
          cargo build --release

      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-${{ matrix.os }}
          path: |
            SOElauncher/target/release/SOElauncher.*
